module.exports = {

    // view
    ADD_PRICE_ALERT: null,
    REMOVE_PRICE_ALERT: null,

    //server
    PRODUCT_PRICE_HISTORY_UPDATE_START: null,
    PRODUCT_PRICE_HISTORY_UPDATE_ERROR: null,
    PRODUCT_PRICE_HISTORY_UPDATE_SUCCESS: null,
    RECEIVE_PRODUCT_PRICE_HISTORY_START : null,
    RECEIVE_PRODUCT_PRICE_HISTORY_ERROR : null,
    RECEIVE_PRODUCT_PRICE_HISTORY_SUCCESS : null
};
